(package "quelpa"
         "1.0"
         "Emacs Lisp packages built directly from source")

(website-url "https://github.com/quelpa/quelpa")
(keywords "tools" "package" "management" "build" "source" "elpa")

(package-file "quelpa.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
