* quelpa

Your personal local Emacs Lisp Package Archive (ELPA) with packages built on-the-fly directly from source.

*Important: quelpa requires at least Emacs 24.3*

If you want to help with the development of quelpa, check the [[https://github.com/quelpa/quelpa/issues][issues.]] The more people we get to work on quelpa, the better :)

** Overview

=quelpa= wants to bring the power over your Emacs packages back to you. The [[http://melpa.milkbox.net/packages/][melpa]] archive is great because it has so many packages but why should an external build service control what packages you can install?

Rather =quelpa= uses recipes in the [[https://github.com/milkypostman/melpa#recipe-format][melpa-format]] to build the packages you want from the source code and installs them to a directory-based local package archive that we call =quelpa=.

You can build and install packages from all the sources the melpa build script (=package-build=) supports:

- git: http://git-scm.com/
- github: https://github.com/
- bazaar (bzr): http://bazaar.canonical.com/en/
- mercurial (hg): http://mercurial.selenic.com/
- subversion (svn): http://subversion.apache.org/
- cvs: http://www.nongnu.org/cvs/
- darcs: http://darcs.net/
- Emacs Wiki (wiki): http://www.emacswiki.org/

** Requirements

- Emacs 24.3
- git: http://git-scm.com/

For any build source you need the corresponding tool. So if you want to install a =subversion= hosted package you need to have =subversion= installed locally.

Important here is to note that if the source for a package is fetched with =git=, it still can have a dependency that may have to be fetched with =mercurial= so you better install the most common ones, i.e. =git=, =bzr=, =hg=, and =svn=.

** Installation

First =quelpa= needs to be bootstrapped, that means melpa's =package-build= has to be installed, then =quelpa= itself.

To bootstrap =quelpa=  use this code:

#+BEGIN_SRC emacs-lisp
(unless (require 'quelpa nil t)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
    (eval-buffer)))
#+END_SRC

To bootstrap =quelpa= now just evaluate this expression in your =*scratch*= buffer. Add it to your Emacs init file to make sure =quelpa= will be installed automatically if necessary.

** Usage

Cool. Now that we are all setup, enjoy the ride.

There are two ways to install packages with =quelpa=:

*** Installing with a package name

Check http://melpa.milkbox.net/ for any packages you would like to install. You only need to know the name:

#+BEGIN_SRC emacs-lisp
(quelpa 'magit)
#+END_SRC

Running this expression will fetch the source code from Github, build a package in elpa format and put it into the local =quelpa=  packages directory =~/.emacs.d/quelpa/packages=. 

The package is installed via the normal =package-install= command behind the scenes.

If the package has dependencies it will install them first.

*** Installing with a recipe

You can also install packages that are not on melpa. For this you need to provide a recipe in the melpa-format.

For example I like the package [[http://www.emacswiki.org/emacs/eval-sexp-fu.el][eval-sexp-fu.el]] which is located on the Emacs Wiki but not available on melpa. I just need to provide a valid recipe instead of a package name:

#+BEGIN_SRC emacs-lisp
(quelpa '(eval-sexp-fu :fetcher wiki :files ("eval-sexp-fu.el")))
#+END_SRC

Don't forget the quote before the recipe. 

*** Managing packages

You can use the Emacs package management interface with =quelpa= . Just start =M-x list-packages= and work with your packages as you normally do.

** Why "quelpa"?

German =Quelle= means =source=, =Quellcode= means =source code= and =ELPA= is short for Emacs Lisp Package Archive, you get the idea. So =quelpa= is your package archive with packages built from source.
