* quelpa

Your personal local Emacs Lisp Package Archive (ELPA) with packages built on-the-fly directly from source.

**Important: quelpa requires at least Emacs 24.3**

If you want to help with the development of quelpa, check the [[https://github.com/quelpa/quelpa/issues][issues.]] The more people we get to work on quelpa, the better :)

** Overview

quelpa wants to bring the power over your Emacs packages back to you. The [[http://melpa.milkbox.net/packages/][melpa]] archive is great because it has so many packages but why should an external build service control what packages you can install?

Rather quelpa uses melpa (and their recipes) to build the packages you want to install from the source code and install them to a directory-based local package archive.

You can build and install packages from all the sources the melpa build script (=package-build=) supports:

- git: http://git-scm.com/
- github: https://github.com/
- bazaar (bzr): http://bazaar.canonical.com/en/
- mercurial (hg): http://mercurial.selenic.com/
- subversion (svn): http://subversion.apache.org/
- cvs: http://www.nongnu.org/cvs/
- darcs: http://darcs.net/
- Emacs Wiki (wiki): http://www.emacswiki.org/

** Installation

First quelpa needs to be bootstrapped, that means the melpa =package-build= has to be installed, then =quelpa= itself.

To bootstrap quelpa use this code:

#+BEGIN_SRC emacs-lisp
(unless (require 'quelpa nil t)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
    (eval-buffer)))
#+END_SRC

To bootstrap quelpa now just evaluate this expression in your =*scratch*= buffer. Add it to your Emacs init file to make sure quelpa will be installed if necessary.

** Usage

Cool. Now that we are all setup enjoy the ride.

Navigate to http://melpa.milkbox.net/ and click on the recipe symbol of a package you'd like to install. Or go directly https://github.com/milkypostman/melpa/blob/master/recipes/ and choose a recipe there.

In this example I use =company=, the alternative auto-completion framework at https://github.com/milkypostman/melpa/blob/master/recipes/company:

#+BEGIN_SRC emacs-lisp
(company :repo "company-mode/company-mode" :fetcher github)
#+END_SRC

Now installing =company= from the Github source with =quelpa= is pretty simple:

#+BEGIN_SRC emacs-lisp
(quelpa '(company :repo "company-mode/company-mode" :fetcher github))
#+END_SRC

Just take care that you put a quote before the recipe. Running this expression will fetch the source code from Github, build a package in elpa format and put it into the local quelpa packages directory =~/.emacs.d/quelpa/packages=. The package is installed via the normal =package-install= command behind the scenes.

You can also use the package management interface with quelpa. Just start =M-x list-packages= and work with your packages as you normally do.

That's currently all folks. More bling to come!

** Why "quelpa"?

German =Quelle= means =source=, =Quellcode= means =source code= and =ELPA= is short for Emacs Lisp Package Archive, you get the idea. So =quelpa= is your package archive with packages built from source.
